config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  get "home", to: "home#index"
  # get 'home/index'

  # get "blagues", to: "blagues#index"
  # get "blague", to: "blagues#show"
  # get 'blagues/show'

  resources :blagues, only: [:show, :index, :new, :edit, :create, :update, :destroy]

  delete 'blagues/:id', to: "blagues#destroy", as: :blague_del

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blague.rb
class Blague < ApplicationRecord
  validates :nom, presence: :true
  validates :contenu, presence: :true
  validates :auteur, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blagues_controller.rb
class BlaguesController < ApplicationController
  def index
    @blagues = Blague.all
  end

  def show
    @blague = Blague.find(params[:id])
  end

  def new
    @blague = Blague.new
  end

  def edit
    @blague = Blague.find(params[:id])
  end

  def create
    @blague = Blague.new(params_blague)
    if @blague.save
      redirect_to @blague
    else
      render :new
    end
  end

  def update
    @blague = Blague.find(params[:id])
    if @blague.update(params_blague)
      redirect_to @blague
    else
      render :edit
    end
  end

  def destroy

    @blague = Blague.find(params[:id])
    @blague.destroy
    redirect_to blagues_path, status: :see_other
  end


  private

  def params_blague
    params.require(:blague).permit(:nom, :contenu, :auteur)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = "Hello, how are you today?"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blagues_helper.rb
module BlaguesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blagues/edit.html.erb
<h2> Modifier la blague</h2>
<div><%= link_to "ttes les Blagues", blagues_path %></div>
<hr>

<%= form_with model: @blague, local: true do |form|%>
  <p>
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </p>

   <p>
    <%= form.label :contenu %>
    <%= form.text_area :contenu %>
  </p>

   <p>
    <%= form.label :auteur %>
    <%= form.text_field :auteur %>
  </p>

  <p>
    <%= form.submit "modifier la blague"%>
  </p>
<% end %>

app/views/blagues/index.html.erb
<h1>ttes les Blagues</h1>
<!--<p>Find me in app/views/blagues/index.html.erb</p>-->

<div><%= link_to 'creer une nouvelle blague',  new_blague_path %></div>
<br>
<hr>
<%@blagues.each do |blague|%>
  <div><h1><%= blague.nom %></h1></div>
  <div><h3>Contenu: </h3> <%= blague.contenu %></div>
  <div><small>publié par: <%= blague.auteur %></small></div>
  <br>
  <div><%= link_to 'voir la blague', blague_path(blague) %></div>
  <hr>
<% end %>

app/views/blagues/new.html.erb
<h1> Publier une nouvelle blague</h1>

<div><%= link_to "ttes les Blagues", blagues_path %></div>
<hr>

<%= form_with model: @blague, local: true do |form|%>
  <!--<% if @blague.errors.any? %>
    <h2>Une erreur est survenu</h2>
    <ul>
      <% @blague.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>-->

  <p>
    <%= form.label :nom %>
    <%= form.text_field :nom %>
  </p>

   <p>
    <%= form.label :contenu %>
    <%= form.text_area :contenu %>
  </p>

   <p>
    <%= form.label :auteur %>
    <%= form.text_field :auteur %>
  </p>

  <p>
    <%= form.submit "publier la blague"%>
  </p>
<% end %>

app/views/blagues/show.html.erb
<h1>Blagues#show</h1>
<!--<p>Find me in app/views/blagues/show.html.erb</p>-->
<div><%= link_to "ttes les Blagues", blagues_path %></div>
<div><%= link_to 'Modifier la blagues', edit_blague_path %></div>


<hr>
<!---->
<div><h1><%= @blague.nom %></h1></div>
<div><h3>Contenu: </h3> <%= @blague.contenu %></div>
<div><small>publié par: <%= @blague.auteur %></small></div>

<!-- delete button-->
<br>
<div><%= button_to "Destroy", blague_del_path(@blague), method: :delete, form: { data: { turbo: true, turbo_confirm: "Are you sure?" } }, class: "delete-link" %>
</div>


<br>

app/views/home/index.html.erb
<!--<div><%= @message %></div>-->

<!--<%= image_tag("brian-lundquist-987aFYyy4YU-unsplash.jpg", :size=>"1*1", :alt=>"image ") %>-->



<div class="container">
  <h1 class="hometitle">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlaguesDroles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>